## 为什么有Async/Await？

Promise虽然跳出了异步嵌套的怪圈，用链式表达更加清晰，但是我们也发现如果有大量的异步请求的时候，流程复杂的情况下，会发现充满了屏幕的then，看起来非常吃力，而ES7的Async/Await的出现就是为了解决这种复杂的情况

## Promise

resolve：将异步的执行从pending(请求)变成了resolve(成功返回)，是个函数执行返回。
reject：顾名思义“拒绝”，就是从请求变成了"失败"，是个函数可以执行返回一个结果，但我们这里推荐大家返回一个错误new Error()

  const setDelay = (millisecond) => {
    return new Promise((resolve, reject)=>{
        if (typeof millisecond != 'number') reject(new Error('参数必须是number类型'));
        setTimeout(()=> {
          resolve(`我延迟了${millisecond}毫秒后输出的`)
        }, millisecond)
    })
  }

  setDelay(3000)
  .then((result)=>{
      console.log(result) // “我延迟了3000毫秒后输出的”
  })

  setDelay(null)
  .then((result)=>{
      console.log(result) 
  })
  .catch((err)=>{
    console.log(err) // “参数必须是number类型”
  })

## Promise相互依赖：

    const setDelaySecond = (seconds) => {
      return new Promise((resolve, reject)=>{
          if (typeof seconds != 'number' || seconds > 10) reject(new Error('参数必须是number类型，并且小于等于10'));
          setTimeout(()=> {
            console.log(`先是setDelaySeconds函数输出，延迟了${seconds}秒，一共需要延迟${seconds+2}秒`)
            resolve(setDelay(2000)) // 这里依赖上一个Promise
          }, seconds * 1000)
      })
    }

    setDelaySecond(3).then((result)=>{
      console.log(result) // 先是setDelaySeconds函数输出，延迟了3秒，一共需要延迟5秒    我延迟了2000毫秒后输出的
    }).catch((err)=>{
      console.log(err);
    })

    const setDelay1 = (delay1) => {
      return new Promise((resolve, reject) => {
        if (typeof delay1 !== 'number') reject (new Error('delay1必须是number'))
        setTimeout(() => {
          resolve(`delay1: ${delay1}`)
        }, delay1)
      })
    }

    setDelay1(3000).then(res => {
      console.log(res)
    }).catch(err => {
      console.log(err)
    })

    const setDelay2 = (delay2) => {
      return new Promise((resolve, reject) => {
        if (typeof delay2 !== 'number') reject (new Error('delay2必须是number'))
        setTimeout(() => {
          console.log(`delay2: ${delay2}`)
          resolve(setDelay1(1000))
        },delay2)
      })
    }

  setDelay2(2000).then(res => {
    console.log(res)
  }).catch(err => {
    console.log(err)
  })


## Promise链式写法:

    const setDelay1 = (delay1) => {
      return new Promise((resolve, reject) => {
        if (typeof delay1 !== 'number') reject (new Error('delay1必须是number'))
        setTimeout(() => {
          resolve(`delay1: ${delay1}`)
        },delay1)
      })
    }

    const setDelay2 = (delay2) => {
      return new Promise((resolve, reject) => {
        if (typeof delay2 !== 'number') reject (new Error('delay2必须是number'))
        setTimeout(() => {
          resolve(`delay2: ${delay2}`)
        },delay2)
      })
    }

    setDelay1('1').then(res => {
      console.log('1:')
      console.log(res)
      return setDelay2(2000)
    }).then(res => {
      console.log('2:')
      console.log(res)
    }).catch(err => {
      console.log(err)
    })



    new Promise((resolve, reject) => {
      setTimeout(() => {
        console.log('1')
        resolve()
      },1000)
    }).then(res => {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          console.log('2')
          resolve()
        },5000)
      })
    }).then(res => {
        setTimeout(() => {
          console.log('3')
        },2000)
    }).catch(err => {
      console.log(err)
    })

## async关键字：
关键字“async”必须声明的是一个函数function，表示“异步函数”。“async”是异步的意思，该关键字声明的异步函数，异步函数的返回值是一个Promise对象。

async function test() {
  return 'abc'
}
<!-- console.log(test()) -->
test().then((data) => {
  console.log(data)
})

## await关键字：
 “await”关键字必须在使用“async”声明的异步函数的内部使用，并且必须是直系的。
 async函数返回一个Promise对象，当函数执行的时候，一旦遇到await就会先返回，等到触发的异步操作完成，再接着执行函数体后面的语句

 async function test() {
  await setTimeout(() => {
    console.log('1')
  },1000)
  console.log('2')
 }

 test() // 2 1

 为什么先输出的下面然后才输出的定时器异步回调呢？那是因为await阻塞等待是有条件的：“如果await后面是Promise对象，会将Promise异步操作转换为同步，线程阻塞等待Promise的resolve/reject返回结果之后，再执行函数体内后面的语句！

 async function test() {
  await new Promise((resolve, reject) => {
    setTimeout(() => {
     console.log('1')
    },1000)
  }) 
  console.log('2')
 }

 test() // 1

 下面的函数体部分竟然没有执行, 因为：“如果await后面是一个Promise对象，那么需要等待这个Promise对象解析完成，如果没有收到resolve或reject函数的返回结果，后面的函数体部分就不会执行。” 

## 如果await后面不是一个Promise对象，那么代码就按照正常的JavaScript顺序执行：先执行同步代码，当主线程空闲了，再去执行异步队列的任务。如果await后面是一个Promise对象，那么线程就会阻塞等待该异步任务完成，并且接受到了Promise对象的返回结果之后才会执行函数体后面部分的代码段